apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mysql-host-forwarder
spec:
  selector:
    matchLabels:
      app: mysql-forwarder
  template:
    metadata:
      labels:
        app: mysql-forwarder
    spec:
      hostNetwork: true
      containers:
        - name: forwarder
          image: alpine/socat
          args:
            - "tcp-listen:3307,fork,reuseaddr"
            - "tcp-connect:127.0.0.1:3306"
          securityContext:
            privileged: true

